### ISSUE TITLE
Sanitise working well

### ISSUE THREAD

**Issue by rockyrelay** [fac26/week1-server-karol-natalia-laura-gareth#40]
Doesn't allow scripting to come through! Nice. 

Does allow block-styling, via `<p>` tag. 

eg
`<em>Help!</em><p>Gp</p>`
creates new block. 

where this doesn't
`<em>Help!</em>Gp`

An issue in the most minor of senses. Overall, works great 😌

**Comment by Kr33L** [comment]
Wow interesting. Thanks. :+1:
